name: CICD
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v5

      # Set up Python environment
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov -r requirements.txt

      # Run unit testcase with coverage
      - name: Run tests with coverage
        run: |
          pytest --cov=src tests/ --cov-report=xml --cov-report=html

      # Upload coverage report
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: |
            coverage.xml
            htmlcov/

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:

      #Step1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      #Step2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      #Step3: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/git-gist-app:latest${{github.run_number}}

      #step4: scan Docker image for vulnerabilities
      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/git-gist-app:latest${{github.run_number}}
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
  deploy:
    name: Deploy to Minikube
    runs-on: self-hosted
    needs: docker
    steps:
      #Step1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      #step2: update image tag in helm chart values.yaml file
      - name: Update image tag in helm chart values.yaml file
        shell: powershell
        run: |
          $filePath = "helm/git-gist-app-chart/values.yaml"
          (Get-Content $filePath) -replace 'tag: "latest"', 'tag: "latest' + $env:GITHUB_RUN_NUMBER + '"' | Set-Content $filePath
          
      # Step3: Deploy to Minikube using Helm
      - name: Deploy to Minikube using Helm
        shell: powershell
        run: |
          helm upgrade --install git-gist-app helm/git-gist-app-chart --namespace git-gist-ns --set image.repository=${{ secrets.DOCKER_HUB_USERNAME }}/git-gist-app --set image.tag=latest${{github.run_number}} --wait